CREATE TABLE CLIENTE (
    ID INTEGER NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    CPF VARCHAR(11) NOT NULL);



/* Primary keys definition */

ALTER TABLE CLIENTE ADD  PRIMARY KEY (ID);


CREATE GENERATOR GN_CLIENTE;
