/* Table: PRODUTO */

CREATE TABLE PRODUTO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    CONTROLEESPECIAL VARCHAR(10) NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL);



/* Primary keys definition */

ALTER TABLE PRODUTO ADD  PRIMARY KEY (ID);

CREATE GENERATOR GN_PRODUTO;
