/* Table: TECNICOAGRICOLA */

CREATE TABLE TECNICOAGRICOLA (
    ID INTEGER NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    NUMEROREGISTRO VARCHAR(30) NOT NULL);



/* Primary keys definition */

ALTER TABLE TECNICOAGRICOLA ADD  PRIMARY KEY (ID);