/* Table: RECEITA */

CREATE TABLE RECEITA (
    ID INTEGER NOT NULL,
    ID_PEDIDO INTEGER,
    STATUS VARCHAR(1),
    ID_TECNICOAGRICOLA INTEGER);



/* Primary keys definition */

ALTER TABLE RECEITA ADD  PRIMARY KEY (ID);


/* Foreign keys definition */

ALTER TABLE RECEITA ADD  CONSTRAINT FK_RECEITA_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOVENDA (ID);
ALTER TABLE RECEITA ADD  CONSTRAINT FK_RECEITA_ID_TECNICOAGRICOLA FOREIGN KEY (ID_TECNICOAGRICOLA) REFERENCES TECNICOAGRICOLA (ID);


CREATE GENERATOR GN_RECEITA;
