/* Table: RECEITAITEM */

CREATE TABLE RECEITAITEM (
    ID INTEGER NOT NULL,
    ID_RECEITA INTEGER,
    ID_PEDIDOVENDAITEM INTEGER);



/* Primary keys definition */

ALTER TABLE RECEITAITEM ADD CONSTRAINT PK_RECEITAITEM PRIMARY KEY (ID);


/* Foreign keys definition */

ALTER TABLE RECEITAITEM ADD  CONSTRAINT FK_RECEITAITEM_IDPEDIDOVENDAITE FOREIGN KEY (ID_PEDIDOVENDAITEM) REFERENCES PEDIDOVENDAITEM (ID);
ALTER TABLE RECEITAITEM ADD  CONSTRAINT FK_RECEITAITEM_ID_RECEITA FOREIGN KEY (ID_RECEITA) REFERENCES RECEITA (ID);


CREATE GENERATOR GN_RECEITAITEM;
